apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: centos
  namespace: dev
spec:
  selector:
    matchLabels:
      app: centos
  replicas: 1
  template:
    metadata:
      labels:
          app: centos
    spec:
      nodeSelector:
        ecaicn.com/persistent-env: dev
      tolerations:
      - operator: "Exists"
      containers:
        - name: centos
          image: centos
          ports:
          - containerPort: 22
          volumeMounts:
          - name: timezone
            mountPath: /etc/timezone
            subPath: timezone
            readOnly: yes
          - name: localtime
            mountPath: /etc/localtime
            readOnly: yes
          command: ["/bin/sh"]
          args: ["-c", "while true; do echo hello; sleep 10;done"]
      volumes:
        - name: timezone
          configMap:
            name: timezone
        - name: localtime
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai